/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import Logic.Department;
import Logic.HR_System;
import Logic.SystemManager;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author pvppl
 */
public class AddNewDepartmentDialog extends javax.swing.JDialog {
    HR_System system;
    private Department departmentToEdit;
    private boolean isEditMode = false;
    private DepartmentsPanel parentPanel;


    /**
     * Creates new form AddNewDepartment
     */
    public AddNewDepartmentDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.system = SystemManager.getInstance().getSystem();
        initComponents();
        setupListeners();
        setLocationRelativeTo(null);
    }
    
    /**
     * Set the parent panel for refreshing after changes
     */
    public void setParentPanel(DepartmentsPanel parentPanel) {
        this.parentPanel = parentPanel;
    }
    
    /**
     * Set up the dialog for editing an existing department
     */
    public void setDepartmentToEdit(Department department) {
        this.departmentToEdit = department;
        this.isEditMode = true;
        
        // Update dialog title and button text
        jLabel1.setText("Edit Department");
        jLabel2.setText("Update department information in the system.");
        btnAddDepartment.setText("Save Changes");
        
        // Populate fields with department data
        departmentNameInput.setText(department.getName());
        txtDepartmentDesc.setText(department.getDescription());
        locationInput.setText(department.getLocation());
        budgetInput.setText(String.valueOf(department.getBudget()));
    }
    
    public void resetForNewDepartment() {
        this.departmentToEdit = null;
        this.isEditMode = false;
        
        // Reset dialog title and button text
        jLabel1.setText("Add New Department");
        jLabel2.setText("Create a new department in the system.");
        btnAddDepartment.setText("Add Department");
        
        // Clear all fields
        clearForm();
    }
    
    private void setupListeners() {
        btnDepartmentCancel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddDepartment = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDepartmentCancel = new javax.swing.JButton();
        departmentNameInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDepartmentDesc = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        locationInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        budgetInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Add New Department");

        btnAddDepartment.setBackground(new java.awt.Color(67, 97, 238));
        btnAddDepartment.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDepartment.setText("Add Department");
        btnAddDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDepartmentActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Create a new department in the system.  ");

        jLabel3.setText("Department Name");

        btnDepartmentCancel.setText("Cancel");

        departmentNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentNameInputActionPerformed(evt);
            }
        });

        jLabel4.setText("Descreption");

        txtDepartmentDesc.setColumns(20);
        txtDepartmentDesc.setRows(5);
        jScrollPane1.setViewportView(txtDepartmentDesc);

        jLabel6.setText("Location");

        locationInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationInputActionPerformed(evt);
            }
        });

        jLabel7.setText("Budget");

        budgetInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDepartmentCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(budgetInput, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(locationInput, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(departmentNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departmentNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(locationInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(budgetInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepartmentCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDepartmentActionPerformed
        try {
            String name = departmentNameInput.getText().trim();
            String description = txtDepartmentDesc.getText().trim();
            String location = locationInput.getText().trim();
            
            // Validate inputs
            if (name.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Department name cannot be empty", 
                        "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (description.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Department description cannot be empty", 
                        "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (location.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Location cannot be empty", 
                        "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Validate budget is a number
            double budget = 0;
            try {
                budget = Double.parseDouble(budgetInput.getText().trim());
                if (budget < 0) {
                    JOptionPane.showMessageDialog(this, "Budget cannot be negative", 
                            "Validation Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Budget must be a valid number", 
                        "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Add department to the system
            system.addDepartment(name, description, location, budget);
            
            // Debug output
            System.out.println("Added department: " + name);
            System.out.println("Total departments now: " + system.listDepartments().size());
            
            JOptionPane.showMessageDialog(this, "Department added successfully", 
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            
            // Clear the form for next entry
            clearForm();
            
            // Optionally close the dialog
            // dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error adding department: " + e.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddDepartmentActionPerformed

    private void departmentNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentNameInputActionPerformed

    private void locationInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationInputActionPerformed

    private void budgetInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_budgetInputActionPerformed

    
    private void clearForm() {
        departmentNameInput.setText("");
        txtDepartmentDesc.setText("");
        locationInput.setText("");
        budgetInput.setText("");
        departmentNameInput.requestFocus();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewDepartmentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewDepartmentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewDepartmentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewDepartmentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddNewDepartmentDialog dialog = new AddNewDepartmentDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private JButton btnCancel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDepartment;
    private javax.swing.JButton btnDepartmentCancel;
    private javax.swing.JTextField budgetInput;
    private javax.swing.JTextField departmentNameInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField locationInput;
    private javax.swing.JTextArea txtDepartmentDesc;
    // End of variables declaration//GEN-END:variables
}
